### ISSUE TITLE
Allow to upgrade all instances at once

### ISSUE THREAD

**Issue by emanuelschuetze** [OpenSlides/openslides-multiinstance-app#22]
Currently each instance has to upgrade manually. It would be useful to upgrade _all_ given instances to a specific new version by one click.

Suggestion: Add a new 'upgrade' button on top of the list view which ask for new version to upgrade all instances. The upgrade process should upgrade one instance after another. Otherwise the server could be very busy if e.g. 40 instances are upgraded simultaneously.

**Comment by boehlke** [comment]
This feature requires backend support and probably a UI showing the status of the upgrade process, or better: Showing a global live status of all instances.

**Comment by jsaalfeld** [comment]
Since Version 1 is released and will be archived and a new backend will be developed, I'll be closing this issue.
